### PR TITLE
update version ember-frost-core

### PR DESCRIPTION
**Pull request by EWhite613**
### This project uses [semver](semver.org), please check the scope of this pr:

- [ ] #none# - documentation fixes and/or test additions
- [ ] #patch# - backwards-compatible bug fix
- [ ] #minor# - adding functionality in a backwards-compatible manner
- [x] #major# - incompatible API change

# CHANGELOG
* Use latest major for `ember-frost-core`

### CODE REVIEW

**Comment by notmessenger** [comment]
* Your Changelog entry is not accurate - you are using latest major
* This PR cannot be a patch - you have changed a dependency to a new major.

**Comment by juwara0** [comment]
The blueprint will need to be updated as well.

**Comment by EWhite613** [comment]
Dependent on https://github.com/ciena-frost/ember-frost-tabs/pull/70 https://github.com/ciena-frost/ember-frost-date-picker/pull/80 https://github.com/ciena-frost/ember-frost-fields/pull/38

**Comment by sophypal** [comment]
👍

**Pull request merged**
