### PR TITLE
Upgrade the world

### PR DESCRIPTION
**Pull request by sandersky**
**This project uses [semver](http://semver.org), please check the scope of this pr:**

- [ ] #patch# - backwards-compatible bug fix
- [ ] #minor# - adding functionality in a backwards-compatible manner
- [x] #major# - incompatible API change

# CHANGELOG

* **Upgraded** all dependencies to the latest.

### CODE REVIEW

**Comment by rox163** [comment]
I don't see the changes I made to destroy-app to fix the test hanging issue

**Comment by sandersky** [comment]
@rox163 I think you are referring to [this](https://github.com/ciena-frost/ember-frost-bunsen/blob/master/tests/helpers/destroy-app.js#L7) which is already in the most recent published version.

**Comment by sglanzer** [comment]
Approved - much win, the LTS is so close I can taste it :)

**Comment by sglanzer** [comment]
@sandersky what are hide and show used for?  UX removed them from the password field in favor of the words and I'm not aware of another usage for the `eye` icons

**Pull request merged**
