### PR TITLE
Change section toggling logic

### PR DESCRIPTION
**Pull request by nskrypnik**
### This project uses [semver](semver.org), please check the scope of this pr:

- [ ] #none# - documentation fixes and/or test additions
- [x] #patch# - backwards-compatible bug fix
- [ ] #minor# - adding functionality in a backwards-compatible manner
- [ ] #major# - incompatible API change

# CHANGELOG
* the logic of toggling section content has been **changed** to hide content with style rather than removing node from rendering in template

### CODE REVIEW

**Comment by sophypal** [comment]
@nskrypnik Looks like you need to update to tests as well.

**Comment by sophypal** [comment]
@nskrypnik Can you rebase your changes.

**Comment by nskrypnik** [comment]
@sophypal rebase is done

**Comment by sophypal** [comment]
👍

**Pull request merged**
