### PR TITLE
Fixes "Could not find module `symbol-observable/polyfill.js`"

### LINKED ISSUE #492: Address Could not find module 'symbol-observable/polyfill.js' imported from 'symbol-observable/index'
See https://github.com/ciena-frost/ember-frost-object-browser/pull/152 for resolution approach

### PR DESCRIPTION
**Pull request by quincyle**
Fixed #492

### This project uses [semver](semver.org), please check the scope of this pr:

- [ ] #none# - documentation fixes and/or test additions
- [x] #patch# - backwards-compatible bug fix
- [ ] #minor# - adding functionality in a backwards-compatible manner
- [ ] #major# - incompatible API change

# CHANGELOG
* **Added** `symbol-observable` at version `1.0.4` to avoid changes being received due to the float: https://github.com/mike-north/ember-symbol-observable/blob/6c6bd65a161b20a9f0f308395ad0553086ca6968/package.json#L50

### CODE REVIEW

**Comment by notmessenger** [comment]
👍

**Comment by sophypal** [comment]
@quincyle Before making these changes, I'm not sure this is even needed. Is it required by Ember? I don't see any references to `Symbol` anywhere in this repo.

**Comment by quincyle** [comment]
@sophypal This is required by `ember-redux` according to @juwara0. Until ember-redux/ember-symbol-observable(same author) release a new version with pinned `symbol-observable` that we can bring into bunsen. We do need this change.

**Comment by sophypal** [comment]
@quincyle Thanks for the info.

**Comment by sophypal** [comment]
👍

**Comment by toranb** [comment]
v1.0.1 of ember-symbol-observable solves this issue :)

https://github.com/mike-north/ember-symbol-observable/releases

**Pull request merged**
