### PR TITLE
correct app.import call in index.js to allow consumption in engine

### PR DESCRIPTION
**Pull request by rox163**
#patch#

### CODE REVIEW

**Comment by sandersky** [comment]
:+1:

**Comment by sglanzer** [comment]
We should start being conscious of the ember-cli and ember versions we require for our addons - nothing urgent, but in the interest of a LTS style release this will be important

**Comment by sandersky** [comment]
@sglanzer maybe we should add older versions to our `ember-try` scenarios?

**Comment by sglanzer** [comment]
That's a good point, we just need to decide what our cutoff is going to be and what time range we want to stabilize over.  Going to be a larger discussion, but it needs to be discussed soonish

**Pull request merged**
